---
# Test Ansible Roles with Molecule and Docker

- name: Print container info
  ansible.builtin.debug:
    var: item

- name: Retrieve container log
  ansible.builtin.command:
    cmd: >-
      {% raw %}
      docker logs
      {% endraw %}
      {{ item.stdout_lines[0] }}
  changed_when: false
  register: logfile_cmd

- name: Display container log
  ansible.builtin.fail:
    var: logfile_cmd.stderr
