ci:
  autofix_commit_msg: "chore: auto fixes from `pre-commit` hooks"
  autoupdate_commit_msg: "chore(pre-commit): autoupdate"
  autoupdate_schedule: quarterly
  skip: [ansible-lint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows
      - id: check-renovate

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/compwa/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/aristanetworks/j2lint
    rev: v1.2.0
    hooks:
      - id: j2lint

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.6.1
    hooks:
      - id: ansible-lint
        args: [--fix]
