---
namespace: deadnews
name: deadnews_template_ansible
version: "0.0.0"
description: Ansible Project Template
readme: README.md
authors:
  - DeadNews <aurczpbgr@mozmail.com>
license:
  - MIT
license_file: LICENSE
repository: https://github.com/DeadNews/deadnews-template-ansible
tags:
  - demo
  - template
  - tools
