[tool.poetry]
name = "deadnews-template-ansible"
version = "0.0.0"
description = "Ansible Project Template"
authors = ["DeadNews <aurczpbgr@mozmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
ansible-core = "^2.15.0"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^6.16.1", markers = "platform_system != 'Windows'" }

[tool.poetry.group.ci.dependencies]
ansible-runner = "^2.3.2"
