---
collections:
  - name: ansible.posix
    version: 1.5.2

  - name: community.general
    version: 8.4.0

  - name: community.docker
    version: 3.8.1

  - name: deadnews.util
    version: 1.0.0-alpha.0
