---
driver:
  name: docker

platforms:
  - name: ${MOLECULE_DISTRO:-debian12}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest

provisioner:
  playbooks:
    converge: ../../../../molecule/playbooks/converge.yml
    create: ../../../../molecule/playbooks/create.yml
    destroy: ../../../../molecule/playbooks/destroy.yml
    prepare: ../../../../molecule/playbooks/prepare-systemctl.yml
