---
driver:
  name: docker

platforms:
  - name: ${MOLECULE_IMAGE:-python}
    image: ${MOLECULE_IMAGE:-python}

provisioner:
  playbooks:
    converge: ../../../../molecule/playbooks/converge.yml
    create: ../../../../molecule/playbooks/create.yml
    destroy: ../../../../molecule/playbooks/destroy.yml
    prepare: ../../../../molecule/playbooks/prepare.yml
