---
argument_specs:
  main:
    short_description: The main entry point for the docker_compose role.
    options:
      docker_compose_project:
        type: str
        required: true
        description: The name of Docker Compose projects which should be deployed.

      docker_compose_source:
        type: str
        default: files/docker-compose.yml
        description: The local path to the Docker Compose file to copy to the remote server.

      docker_compose_target_dir:
        type: str
        default: ~/docker-compose
        description: The directory where the Docker Compose projects should create respective directories.

      docker_compose_env:
        type: str
        required: false
        description: The local path to the Environment file to copy to the remote server.

      docker_compose_env_template:
        type: str
        required: false
        description: The local path to the Environment file template to copy to the remote server.
