---
platforms:
  - name: molecule-distro
    image: ${MOLECULE_DISTRO:-python}

provisioner:
  name: ansible
  playbooks:
    create: ../../../../molecule/playbooks/create.yml
    destroy: ../../../../molecule/playbooks/destroy.yml
    prepare: ../../../../molecule/playbooks/prepare.yml
