---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: jammy
    box: ubuntu/jammy64
    config_options:
      vm.boot_timeout: 600
    memory: 1024

provisioner:
  name: ansible
