---
networks:
  traefik_public:
    external: true
  socket_proxy:
    external: false

services:
  traefik:
    image: traefik:3.0.0@sha256:7996bdae8aaa70eaacf2978b6c949de5b68c0a24ddc3e40c06344ecc88cfaea3
    container_name: traefik
    networks:
      - traefik_public
      - socket_proxy
    depends_on:
      - socket_proxy
    ports:
      # "web" HTTP listener
      - "0.0.0.0:80:80/tcp"
      # "traefik" internal services
      - 127.0.0.1:8080:8080/tcp
    command:
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --metrics.prometheus=true
      - --ping=true
      - --providers.docker.endpoint=tcp://socket_proxy:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_public
      - --providers.docker=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_route.entrypoints=web
      - traefik.http.routers.api_route.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api_route.service=api@internal
    healthcheck:
      test: [CMD, traefik, healthcheck, --ping]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Security-enhanced proxy for the Docker Socket
  socket_proxy:
    image: tecnativa/docker-socket-proxy:0.1.2@sha256:dc8ec925b1360c54e6bf350602d6faac4e33c5d8d809118e4c000c0b14a4529a
    restart: unless-stopped
    networks:
      - socket_proxy
    volumes:
      - ${XDG_RUNTIME_DIR:-/var/run}/docker.sock:/var/run/docker.sock:ro
    environment:
      NETWORKS: 1
      SERVICES: 1
      CONTAINERS: 1
      TASKS: 1
