---
version: "3"
services:
  reverse-proxy:
    image: traefik:3.0.0-rc1@sha256:916a4a86b36bb3576f39883573b0f932ed3f010bbbf35feab115bdbd5033566b
    command:
      - --api.insecure=true # Traefik will listen on port 8080 by default for API request
      - --providers.docker=true # Enabling Docker provider
      - --providers.docker.exposedbydefault=false # Do not expose containers unless explicitly told so
      - --entrypoints.web.address=:80 # Traefik will listen to incoming request on the port 80 (HTTP)
    ports:
      - 8000:8000 # The HTTP port
      - 8080:8080 # The Web UI (enabled by --api.insecure=true)
    volumes:
      - ${XDG_RUNTIME_DIR:-/var/run/}/docker.sock:/var/run/docker.sock:ro
