---
# Install Grafana Loki (Example)

- name: Check distribution compatibility
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Debian'

- name: Add Grafana repository
  ansible.builtin.deb822_repository:
    name: grafana
    types: [deb]
    architectures: amd64
    uris: https://apt.grafana.com
    signed_by: https://apt.grafana.com/gpg.key
    suites: [stable]
    components: [main]
    state: present

- name: Install Grafana Loki
  ansible.builtin.apt:
    name: loki
    state: latest
    update_cache: true
    allow_change_held_packages: true
  notify: (Handler) Restart Grafana Loki service

- name: Hold Grafana Loki
  ansible.builtin.dpkg_selections:
    name: loki
    selection: hold

- name: Create directory for Loki data
  ansible.builtin.file:
    path: /data/loki
    state: directory
    owner: loki
    mode: "0755"

- name: Replace config file for Grafana Loki
  ansible.builtin.template:
    src: templates/loki.yml.j2
    dest: /etc/loki/config.yml
    mode: "0664"
    validate: loki -verify-config -config.file %s
  notify: (Handler) Restart Grafana Loki service

- name: Flush handlers after deployment
  ansible.builtin.meta: flush_handlers

- name: Ensure that Grafana Loki is started
  ansible.builtin.systemd:
    name: loki
    state: started

- name: Verify that Grafana Loki URL is responding
  ansible.builtin.uri:
    url: http://127.0.0.1:3100/ready
  register: loki_verify
  retries: 5
  delay: 8
  until: loki_verify is not failed
