---
# Deploy Traefik

- name: Install Docker
  ansible.builtin.import_role:
    name: deadnews.util.docker
  vars:
    docker_rootless: false

- name: Create a network for Traefik
  community.docker.docker_network:
    name: traefik

- name: Deploy Traefik
  ansible.builtin.import_role:
    name: deadnews.util.docker_compose
  vars:
    docker_compose_project: traefik
    docker_compose_target_dir: ~/docker-compose
    docker_compose_files:
      - src: files/docker-compose.yml
    docker_compose_files_show: true
    docker_compose_sleep_time: 2
    docker_compose_containers_logs:
      - traefik
      - socket-proxy
    docker_compose_containers_check:
      - traefik
      - socket-proxy
      - whoami

- name: Verify that Traefik is responding
  ansible.builtin.uri:
    url: http://127.0.0.1:8080/ping
  register: traefik_verify
  retries: 12
  delay: 5
  until: traefik_verify is not failed

- name: Verify that Whoami is responding
  ansible.builtin.uri:
    url: http://127.0.0.1:80
    headers:
      Host: whoami.localhost
  register: traefik_verify
  retries: 12
  delay: 5
  until: traefik_verify is not failed
