---
# Deploy Traefik

- name: Install Docker
  ansible.builtin.import_role:
    name: deadnews.util.docker
  vars:
    docker_rootless: false

- name: Create a network for Traefik
  community.docker.docker_network:
    name: traefik-public

- name: Deploy Traefik
  ansible.builtin.import_role:
    name: deadnews.util.docker_compose
  vars:
    docker_compose_project: traefik
    docker_compose_target_dir: ~/docker-compose
    docker_compose_files:
      - src: files/docker-compose.yml
    docker_compose_containers_check:
      - traefik

- name: Verify that Traefik is responding
  ansible.builtin.uri:
    url: http://127.0.0.1:8080/ping
  register: traefik_verify
  retries: 5
  delay: 8
  until: traefik_verify is not failed
