---
platforms:
  - name: molecule-ubuntu
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: molecule/default/converge.yml
    create: molecule/default/create.yml
    destroy: molecule/default/destroy.yml
