---
# Install docker-systemctl-replacement to allow systemd commands to be run in a container

- name: Prepare
  hosts: all
  vars:
    version: 1.5.8066 # renovate: datasource=pypi dep_name=docker-systemctl-replacement

  tasks:
    - name: Update apt cache
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        update_cache: true

    - name: Ensure directory for systemctl-replacement
      ansible.builtin.file:
        path: /systemctl-replacement/
        state: directory
        mode: "0755"

    - name: Install systemctl.py
      ansible.builtin.pip:
        name: docker-systemctl-replacement=={{ version }}
        extra_args: --target=/systemctl-replacement/
      register: pip_install

    - name: Ensure systemctl.py is installed
      ansible.builtin.debug:
        var: pip_install

    - name: Check if systemctl.py is installed
      ansible.builtin.command:
        cmd: ls -lh /systemctl-replacement/
      changed_when: false
      register: systemctl_stat

    - name: Ensure systemctl.py
      ansible.builtin.debug:
        var: systemctl_stat

    - name: Replace systemctl
      ansible.builtin.copy:
        src: /systemctl-replacement/systemctl.py
        dest: /usr/bin/systemctl
        remote_src: true
        mode: "0755"

    - name: Ensure run directory for ansible check_systemd
      ansible.builtin.file:
        name: /run/systemd/system/
        state: directory
        mode: "0755"
