---
# Install docker-systemctl-replacement to allow systemd commands to be run in a container

- name: Prepare
  hosts: all
  vars:
    version: 1.5.8066 # renovate: datasource=pypi dep_name=docker-systemctl-replacement
  tasks:
    - name: Install systemctl.py
      ansible.builtin.pip:
        name: docker-systemctl-replacement=={{ version }}
        extra_args: --target=/tmp/dsr

    - name: Replace systemctl
      ansible.builtin.copy:
        src: /tmp/dsr/systemctl.py
        dest: /usr/bin/systemctl
        remote_src: true
        mode: "0755"

    - name: Ensure run directory for ansible check_systemd
      ansible.builtin.file:
        name: /run/systemd/system/
        state: directory
        mode: "0755"
