---
# Install systemd

- name: Prepare
  hosts: all

  tasks:
    - name: Update apt cache
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        update_cache: true

    - name: Install systemd
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name:
          - systemd
          - systemd-sysv
        state: present
